
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace _ExcellOn_.Models
{

    using System;
    using System.Collections.Generic;

    public partial class Customer
    {

        public Customer()
        {

            this.Orders = new HashSet<Order>();

        }


        public int Id { get; set; }

        public string Customer_Name { get; set; }

        public string Customer_Phone { get; set; }

        public string Customer_Email { get; set; }

        public string Customer_UserName { get; set; }

        public string Customer_Password { get; set; }

        public Nullable<int> CompanyId { get; set; }

        public string Customer_Comment { get; set; }

        public string Customer_Avatar { get; set; }

        public Nullable<int> Customer_Gender { get; set; }



        public virtual Company Company { get; set; }

        public virtual ICollection<Order> Orders { get; set; }

    }

}
