

//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace _ExcellOn_.Models
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class Entities : DbContext
{
    public Entities()
        : base("name=Entities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public DbSet<Company> Companies { get; set; }

    public DbSet<Customer> Customers { get; set; }

    public DbSet<Image> Images { get; set; }

    public DbSet<OrderDetail> OrderDetails { get; set; }

    public DbSet<Order> Orders { get; set; }

    public DbSet<Permission> Permissions { get; set; }

    public DbSet<PermissionRole> PermissionRoles { get; set; }

    public DbSet<Role> Roles { get; set; }

    public DbSet<Service> Services { get; set; }

    public DbSet<Staff> Staffs { get; set; }

    public DbSet<Staff_OrderDetail> Staff_OrderDetail { get; set; }

    public DbSet<sysdiagram> sysdiagrams { get; set; }

    public DbSet<UserInFo> UserInFoes { get; set; }

    public DbSet<UserRole> UserRoles { get; set; }

    public DbSet<MyCompany> MyCompanies { get; set; }

}

}

