
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace _ExcellOn_.Models
{

using System;
    using System.Collections.Generic;
    
public partial class MyCompany
{

    public int Id { get; set; }

    public string Title { get; set; }

    public string Image { get; set; }

    public string Description { get; set; }

    public string Address { get; set; }

    public string TaxIdentificationNumber { get; set; }

    public string MyMission { get; set; }

    public string MyVision { get; set; }

    public string MyTarget { get; set; }

}

}
