
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace _ExcellOn_.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Permission
{

    public Permission()
    {

        this.PermissionRoles = new HashSet<PermissionRole>();

    }


    public int Id { get; set; }

    public string Permission_Name { get; set; }

    public Nullable<int> Parent_id { get; set; }

    public string Key_code { get; set; }



    public virtual ICollection<PermissionRole> PermissionRoles { get; set; }

}

}
