
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace _ExcellOn_.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Service
{

    public Service()
    {

        this.Images = new HashSet<Image>();

        this.OrderDetails = new HashSet<OrderDetail>();

        this.Staffs = new HashSet<Staff>();

    }


    public int Id { get; set; }

    public string Service_Name { get; set; }

    public Nullable<double> Service_Price { get; set; }

    public string Service_Description { get; set; }

    public Nullable<int> Service_SaleStatus { get; set; }

    public string Service_Image { get; set; }

    public Nullable<double> Service_PriceSale { get; set; }



    public virtual ICollection<Image> Images { get; set; }

    public virtual ICollection<OrderDetail> OrderDetails { get; set; }

    public virtual ICollection<Staff> Staffs { get; set; }

}

}
