
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace _ExcellOn_.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Staff
{

    public Staff()
    {

        this.Staff_OrderDetail = new HashSet<Staff_OrderDetail>();

    }


    public int Id { get; set; }

    public string Staff_UserName { get; set; }

    public string Staff_Password { get; set; }

    public string Staff_Email { get; set; }

    public Nullable<int> Staff_Gender { get; set; }

    public Nullable<int> Staff_Age { get; set; }

    public Nullable<int> Staff_Status { get; set; }

    public string Staff_Phone { get; set; }

    public string Staff_Address { get; set; }

    public string Staff_Avatar { get; set; }

    public string Staff_FullName { get; set; }

    public string Staff_AboutMe { get; set; }

    public Nullable<int> ServiceId { get; set; }



    public virtual Service Service { get; set; }

    public virtual ICollection<Staff_OrderDetail> Staff_OrderDetail { get; set; }

}

}
