
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace _ExcellOn_.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Staff_OrderDetail
{

    public int Id { get; set; }

    public Nullable<System.DateTime> Date_Start { get; set; }

    public Nullable<System.DateTime> Date_End { get; set; }

    public Nullable<int> Staff_Id { get; set; }

    public Nullable<int> OrderDetail_Id { get; set; }



    public virtual OrderDetail OrderDetail { get; set; }

    public virtual Staff Staff { get; set; }

}

}
