
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace _ExcellOn_.Models
{

using System;
    using System.Collections.Generic;
    
public partial class UserInFo
{

    public UserInFo()
    {

        this.UserRoles = new HashSet<UserRole>();

    }


    public int Id { get; set; }

    public string User_Name { get; set; }

    public string User_Password { get; set; }

    public string User_Email { get; set; }

    public Nullable<int> User_Gender { get; set; }

    public Nullable<int> User_Age { get; set; }

    public string User_Phone { get; set; }

    public string User_Address { get; set; }

    public string User_Avatar { get; set; }

    public string User_FullName { get; set; }

    public string User_AboutMe { get; set; }



    public virtual ICollection<UserRole> UserRoles { get; set; }

}

}
